# -*- coding: utf-8 -*-
"""Problema_CambioMoneda.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ES0gP5jqcLoe-ASrQxpXKgndqB1Ki61J
"""

def cambio_de_moneda(monedas, cantidad, indice):
    # Caso base: si la cantidad es 0, se ha encontrado una combinación válida
    if cantidad == 0:
        return 1

    # Si la cantidad es negativa o ya no hay más monedas para considerar, no hay solución
    if cantidad < 0 or indice >= len(monedas):
        return 0

    # Se llama recursivamente considerando dos casos:
    # 1. Incluir la moneda actual en la combinación y restar su valor a la cantidad
    # 2. Excluir la moneda actual de la combinación y mantener la cantidad sin cambios
    return cambio_de_moneda(monedas, cantidad - monedas[indice], indice) + cambio_de_moneda(monedas, cantidad, indice + 1)

# Ejemplo de uso
monedas = [1, 2, 5]
cantidad_objetivo = 5
formas_cambio = cambio_de_moneda(monedas, cantidad_objetivo, 0)
print("Número de formas distintas de obtener la cantidad objetivo:", formas_cambio)